---
title: "Title"
author: "Andrew Fahmy, Zack Larson, Julia Lundstrum, Nikole Slinger, Dana Thacker"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(readxl)
library(ggthemes)
library(mapproj)

raw_data <- readxl::read_xlsx("2021VaccineCovidData.xlsx", sheet='raw_data')
VAERSdata <- readxl::read_xlsx("2021VaccineCovidData.xlsx", sheet='2021VAERSDATA')
VAERSsymptoms <- readxl::read_xlsx("2021VaccineCovidData.xlsx", sheet='2021VAERSSymptoms')
VAERSVax <- readxl::read_xlsx("2021VaccineCovidData.xlsx", sheet='2021VAERSVax')
cdcdoses <- readxl::read_xlsx("2021VaccineCovidData.xlsx", sheet='2021AllVaccines')
state <- map_data("state")
abbrev <- read.csv("csvData.csv", stringsAsFactors = FALSE)
```

### Introduction



### Background Information
(Not sure if we want to add a part for this)


### Research Questions

- Which states have the highest and lowest number of Covid-19 cases and fatality rates?
- What is the most popular vaccine manufacturer in each state?
- How do Covid-19 cases compare to the number of vaccines administered per state?
- What age group has recieved the most vaccines?
- What is the most common symptom to experience for each manufacturer?
- How does a patient's medical history compare to their symptoms after receiving the vaccine?
- What is the trend on the number of reported adverse effect from vaccines administered per day? Does the trend differ between states and nation wide?
- What patterns are shown when looking at a patient's death (post-vaccinnation) and the reasons why they might have died?

### Obtaining and Cleaning the Data



### Exploratory Analysis

**Which states have the highest and lowest number of Covid-19 cases and fatality rates?**


**What is the most popular vaccine manufacturer in each state?**


**How do Covid-19 cases compare to the number of vaccines administered per state?**


**What age group has recieved the most vaccines?**


**What is the most common symptom to experience for each manufacturer?**


**How does a patient's medical history compare to their symptoms after receiving the vaccine?**


**What is the trend on the number of reported adverse effect from vaccines administered per day? Does the trend differ between states and nation wide?**


**What patterns are shown when looking at a patient's death (post-vaccinnation) and the reasons why they might have died?**


### Challenges Faced



### Conclusion



### Personal Contributions



### Works Cited








